### ISSUE TITLE
using dMRIprep for the first time

### ISSUE THREAD

**Issue by Meryam1985** [nipreps/dmriprep#160]
* dmriprep version:dMRIPrep v0.5.0
* Python version:3.8
* Operating System:ubuntu

### Description

Hello
I am converting the data to BIDS format.
I tried the following command line:dmriprep --fs-license-file /home/besma/Desktop/test/derivatives /home/besma/Desktop/fmriprepp/Nifti/sub-002S1155/ses-002/ /home/besma/Desktop/fmriprepp/Dmri/ participant
I got this error:Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/besma/.local/lib/python3.8/site-packages/dmriprep/cli/workflow.py", line 85, in build_workflow
    retval["workflow"] = init_dmriprep_wf()
  File "/home/besma/.local/lib/python3.8/site-packages/dmriprep/workflows/base.py", line 46, in init_dmriprep_wf
    BIDSFreeSurferDir(
  File "/home/besma/.local/lib/python3.8/site-packages/nipype/interfaces/base/core.py", line 647, in __init__
    super(SimpleInterface, self).__init__(
  File "/home/besma/.local/lib/python3.8/site-packages/nipype/interfaces/base/core.py", line 191, in __init__
    self.inputs.trait_set(**inputs)
  File "/home/besma/.local/lib/python3.8/site-packages/traits/has_traits.py", line 1434, in trait_set
    setattr(self, name, value)
  File "/home/besma/.local/lib/python3.8/site-packages/nipype/interfaces/base/traits_extension.py", line 131, in validate
    self.error(objekt, name, str(value))
  File "/home/besma/.local/lib/python3.8/site-packages/traits/base_trait_handler.py", line 74, in error
    raise TraitError(
traits.trait_errors.TraitError: The 'freesurfer_home' trait of a _BIDSFreeSurferDirInputSpec instance must be a pathlike object or string representing an existing directory, but a value of 'None' <class 'str'> was specified.

If anyone can help me. I would be grateful.
Thank you.

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by Meryam1985** [comment]
I had a path problem and now it's solved
cordially

**Comment by josephmje** [comment]
Sorry for missing this @Meryam1985. Glad that you were able to figure it out and hopefully we can respond sooner to any future issues.

**Comment by chengyu89527** [comment]
> Sorry for missing this @Meryam1985. Glad that you were able to figure it out and hopefully we can respond sooner to any future issues.



> 
sorry I have a same issue, can you tell me how to solve it?
