### ISSUE TITLE
[WARNING] Citeproc: citation eddy not found

### ISSUE THREAD

**Issue by celprov** [nipreps/dmriprep#202]
### What happened?

Everytime I run dMRIPrep this warning appears.

### What command did you use?

```shell
singularity run -e 
-B $DATADIR/inputs:/data:ro \
-B ${WORKDIR}:/work \
-B ${OUTDIR}:/out \
-B `pwd`/license.txt:/opt/freesurfer/license.txt \
-B `pwd`/filter_file_$SES.json:/filter_file_$SES.json \
-B ${HOME}/.cache/templateflow/tpl-MNI152NLin6Asym/:${HOME}/.cache/templateflow/tpl-MNI152NLin6Asym/ 
$PATCHES \
-B /oak/stanford/groups/russpold/inprocess/cprovins/hcph-pilot/code/dmriprep/dmriprep:/usr/local/miniconda/lib/python3.7/site-packages/dmriprep/ \
/users/cprovins/singularity_images/dmriprep-0.5.0.simg /data /out/dmriprep-0.5.0 participant \
-w /work --bids-filter-file /filter_file_$SES.json --skip-bids-validation \
--nprocs 4 --mem 45G --omp-nthreads 2 --ignore fieldmaps \
--anat-only -vv
```

### What version of the software are you running?

0.5.0

### How are you running this software?

Singularity

### Is your data BIDS valid?

Yes

### Are you reusing any previously computed results?

No

### Please copy and paste any relevant log output.

```shell
--- Logging error ---
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/logging/__init__.py", line 1034, in emit
    msg = self.format(record)
  File "/usr/local/miniconda/lib/python3.7/logging/__init__.py", line 880, in format
    return fmt.format(record)
  File "/usr/local/miniconda/lib/python3.7/logging/__init__.py", line 619, in format
    record.message = record.getMessage()
  File "/usr/local/miniconda/lib/python3.7/logging/__init__.py", line 380, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/local/miniconda/bin/dmriprep", line 8, in <module>
    sys.exit(main())
  File "/usr/local/miniconda/lib/python3.7/site-packages/dmriprep/cli/run.py", line 25, in main
    "To opt out, call dmriprep with a `--notrack` flag",
Message: 'Your usage of dmriprep is being recorded using popylar (https://popylar.github.io/). '
Arguments: ('For details, see https://nipreps.github.io/dmriprep/usage.html. ', 'To opt out, call dmriprep with a `--notrack` flag')
--- Logging error ---
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/logging/__init__.py", line 1034, in emit
    msg = self.format(record)
  File "/usr/local/miniconda/lib/python3.7/logging/__init__.py", line 880, in format
    return fmt.format(record)
  File "/usr/local/miniconda/lib/python3.7/logging/__init__.py", line 619, in format
    record.message = record.getMessage()
  File "/usr/local/miniconda/lib/python3.7/logging/__init__.py", line 380, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/local/miniconda/bin/dmriprep", line 8, in <module>
    sys.exit(main())
  File "/usr/local/miniconda/lib/python3.7/site-packages/dmriprep/cli/run.py", line 25, in main
    "To opt out, call dmriprep with a `--notrack` flag",
Message: 'Your usage of dmriprep is being recorded using popylar (https://popylar.github.io/). '
Arguments: ('For details, see https://nipreps.github.io/dmriprep/usage.html. ', 'To opt out, call dmriprep with a `--notrack` flag')
[WARNING] Citeproc: citation eddy not found
```

**Comment by trinhdh** [comment]
I faced the exact issue.
Would you mind sharing how do you overcome this ?

Thank you so much

**Comment by celprov** [comment]
Hello @trinhdh,
I'm sorry it has been too long, so I don't remember if I overcame it and how. I would tend to think that I did not investigate the issue further than just reporting it because it was not an urgent matter for me at the time.
